<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="LAPTOP-MAIB2V06" failures="1" tests="2" name="Test(failed)" time="128.476" errors="0" timestamp="2025-01-31T21:36:10 IST">
  <testcase classname="Campaign.createcampwithproductTest" name="createcampwithproductTest" time="36.137">
    <failure type="java.lang.AssertionError" message="expected [cinthol411] but found [cinthol271]">
      <![CDATA[java.lang.AssertionError: expected [cinthol411] but found [cinthol271]
at Campaign.createcampwithproductTest.createcampwithproductTest(createcampwithproductTest.java:88)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- createcampwithproductTest -->
  <testcase classname="Campaign.createcampaignTest" name="createcampaignTest" time="9.274"/>
  <testcase classname="Generic_Utilities.BaseClass" name="@BeforeSuite BS" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite BS -->
  <testcase classname="Generic_Utilities.BaseClass" name="@BeforeTest BT" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest BT -->
  <testcase classname="Generic_Utilities.BaseClass" name="@AfterSuite AS" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite AS -->
  <testcase classname="Generic_Utilities.BaseClass" name="@AfterTest AT" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest AT -->
</testsuite> <!-- Test(failed) -->
