<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="LAPTOP-MAIB2V06" failures="1" tests="2" name="TestRunner2" time="124.426" errors="0" timestamp="2025-02-05T19:43:14 IST">
  <testcase classname="Campaign.createcampwithproductTest" name="createcampwithproductTest" time="62.12">
    <failure type="java.lang.AssertionError" message="expected [cinthol591] but found [cinthol271]">
      <![CDATA[java.lang.AssertionError: expected [cinthol591] but found [cinthol271]
at Campaign.createcampwithproductTest.createcampwithproductTest(createcampwithproductTest.java:88)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- createcampwithproductTest -->
  <testcase classname="organisation.CreateOrganisationTest" name="CreateOrganisationTest" time="29.371"/>
  <testcase classname="Generic_Utilities.BaseClass" name="@BeforeSuite BS" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite BS -->
  <testcase classname="Generic_Utilities.BaseClass" name="@BeforeTest BT" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest BT -->
  <testcase classname="Generic_Utilities.BaseClass" name="@AfterSuite AS" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite AS -->
  <testcase classname="Generic_Utilities.BaseClass" name="@AfterTest AT" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest AT -->
</testsuite> <!-- TestRunner2 -->
